<?php
/**
 * Registering Theme Default Layout templates
 *
 * @author jason.xie@victheme.com
 *
 */
class VTCore_History_Filters_VC__Load__Default__Templates
extends VTCore_Wordpress_Models_Hook {

  public function hook($templates = NULL) {

    // Lapas team member details block
    array_unshift($templates, array(
      'name' => __('* History Elements', 'medikal'),
      'custom_class' => 'vtcore-history',
      'content' =>
<<<CONTENT
[vc_row full_width="" parallax="" parallax_image="" css=""][vc_column width="1/1"][history connector="1" curvex="0" curvey="100" startx="0" starty="0" endx="0" endy="0" linewidth="10" linetype="round"][historyinner enable___title="true" enable___subtitle="true" title="Example Title" subtitle="Example SubTitle" enable___image="true" image_attachmentid="48" image_position="left" image_style="vc_box_shadow_circle_2" border_color="grey" enable___icon="true" enable___label="true" label_text="label" label_label="default" data_curve_x="0" data_curve_y="100" data_offset_start_x="0" data_offset_start_y="0" data_offset_end_x="0" data_offset_end_y="0" data_linewidth="10" data_linetype="round" direction="left" title_class="text-bold" image_size="full" icon_icon="anchor" icon_size="3x" icon_rotate="0" icon_flip="0" icon_spin="0" icon_border="0" icon_shape="circle" icon_position="pull-center" grids___columns___mobile="12" grids___columns___tablet="10" grids___columns___small="10" grids___columns___large="10" grids___offset___mobile="0" grids___offset___tablet="0" grids___offset___small="0" grids___offset___large="0" grids___push___mobile="0" grids___push___tablet="0" grids___push___small="0" grids___push___large="0" grids___pull___mobile="0" grids___pull___tablet="0" grids___pull___small="0" grids___pull___large="0" left_grids___columns___mobile="12" left_grids___columns___tablet="6" left_grids___columns___small="6" left_grids___columns___large="6" left_grids___offset___mobile="0" left_grids___offset___tablet="0" left_grids___offset___small="0" left_grids___offset___large="0" left_grids___push___mobile="0" left_grids___push___tablet="0" left_grids___push___small="0" left_grids___push___large="0" left_grids___pull___mobile="0" left_grids___pull___tablet="0" left_grids___pull___small="0" left_grids___pull___large="0" right_grids___columns___mobile="12" right_grids___columns___tablet="6" right_grids___columns___small="6" right_grids___columns___large="6" right_grids___offset___mobile="0" right_grids___offset___tablet="0" right_grids___offset___small="0" right_grids___offset___large="0" right_grids___push___mobile="0" right_grids___push___tablet="0" right_grids___push___small="0" right_grids___push___large="0" right_grids___pull___mobile="0" right_grids___pull___tablet="0" right_grids___pull___small="0" right_grids___pull___large="0" css=".vc_custom_1437355626536{margin-bottom: 100px !important;}" icon_color="#ffffff" icon_background="#2c94cc" icon_inner_padding="15px" icon_font="30px" icon_width="60px" icon_height="60px" data_gradientone="#2394db" data_gradienttwo="#1d5ec1"][vc_column_text css_animation=""]

I am text block. Click edit button to change this text. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.

[/vc_column_text][/historyinner][historyinner enable___title="true" enable___subtitle="true" title="Example Title" subtitle="Example SubTitle" enable___image="true" image_attachmentid="48" image_position="left" image_style="vc_box_shadow_circle_2" border_color="grey" enable___icon="true" enable___label="true" label_text="label" label_label="default" data_curve_x="0" data_curve_y="100" data_offset_start_x="0" data_offset_start_y="0" data_offset_end_x="0" data_offset_end_y="0" data_linewidth="10" data_linetype="round" direction="right" title_class="text-bold" image_size="full" icon_icon="android" icon_size="0" icon_rotate="0" icon_flip="0" icon_spin="0" icon_border="0" icon_shape="circle" icon_position="pull-center" grids___columns___mobile="12" grids___columns___tablet="10" grids___columns___small="10" grids___columns___large="10" grids___offset___mobile="0" grids___offset___tablet="2" grids___offset___small="2" grids___offset___large="2" grids___push___mobile="0" grids___push___tablet="0" grids___push___small="0" grids___push___large="0" grids___pull___mobile="0" grids___pull___tablet="0" grids___pull___small="0" grids___pull___large="0" left_grids___columns___mobile="12" left_grids___columns___tablet="6" left_grids___columns___small="6" left_grids___columns___large="6" left_grids___offset___mobile="0" left_grids___offset___tablet="0" left_grids___offset___small="0" left_grids___offset___large="0" left_grids___push___mobile="0" left_grids___push___tablet="0" left_grids___push___small="0" left_grids___push___large="0" left_grids___pull___mobile="0" left_grids___pull___tablet="0" left_grids___pull___small="0" left_grids___pull___large="0" right_grids___columns___mobile="12" right_grids___columns___tablet="6" right_grids___columns___small="6" right_grids___columns___large="6" right_grids___offset___mobile="0" right_grids___offset___tablet="0" right_grids___offset___small="0" right_grids___offset___large="0" right_grids___push___mobile="0" right_grids___push___tablet="0" right_grids___push___small="0" right_grids___push___large="0" right_grids___pull___mobile="0" right_grids___pull___tablet="0" right_grids___pull___small="0" right_grids___pull___large="0" css=".vc_custom_1437355648522{margin-bottom: 100px !important;}" icon_inner_padding="15px" icon_font="30px" icon_width="60px" icon_height="60px" icon_color="#ffffff" icon_background="#a4ea00" data_gradientone="#57f427" data_gradienttwo="#009e17"][vc_column_text css_animation=""]

I am text block. Click edit button to change this text. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.

[/vc_column_text][/historyinner][historyinner enable___title="true" enable___subtitle="true" title="Example Title" subtitle="Example SubTitle" enable___image="true" image_attachmentid="48" image_position="left" image_style="vc_box_shadow_circle_2" border_color="grey" enable___icon="true" enable___label="true" label_text="label" label_label="default" data_curve_x="0" data_curve_y="100" data_offset_start_x="0" data_offset_start_y="0" data_offset_end_x="0" data_offset_end_y="0" data_linewidth="10" data_linetype="round" direction="left" title_class="text-bold" image_size="full" icon_icon="apple" icon_size="0" icon_rotate="0" icon_flip="0" icon_spin="0" icon_border="0" icon_shape="circle" icon_position="pull-center" grids___columns___mobile="12" grids___columns___tablet="10" grids___columns___small="10" grids___columns___large="10" grids___offset___mobile="0" grids___offset___tablet="0" grids___offset___small="0" grids___offset___large="0" grids___push___mobile="0" grids___push___tablet="0" grids___push___small="0" grids___push___large="0" grids___pull___mobile="0" grids___pull___tablet="0" grids___pull___small="0" grids___pull___large="0" left_grids___columns___mobile="12" left_grids___columns___tablet="6" left_grids___columns___small="6" left_grids___columns___large="6" left_grids___offset___mobile="0" left_grids___offset___tablet="0" left_grids___offset___small="0" left_grids___offset___large="0" left_grids___push___mobile="0" left_grids___push___tablet="0" left_grids___push___small="0" left_grids___push___large="0" left_grids___pull___mobile="0" left_grids___pull___tablet="0" left_grids___pull___small="0" left_grids___pull___large="0" right_grids___columns___mobile="12" right_grids___columns___tablet="6" right_grids___columns___small="6" right_grids___columns___large="6" right_grids___offset___mobile="0" right_grids___offset___tablet="0" right_grids___offset___small="0" right_grids___offset___large="0" right_grids___push___mobile="0" right_grids___push___tablet="0" right_grids___push___small="0" right_grids___push___large="0" right_grids___pull___mobile="0" right_grids___pull___tablet="0" right_grids___pull___small="0" right_grids___pull___large="0" css=".vc_custom_1437355664321{margin-bottom: 100px !important;}" icon_inner_padding="15px" icon_font="30px" icon_width="60px" icon_height="60px" icon_color="#ffffff" icon_background="#ff26a4" data_gradientone="#c523dd" data_gradienttwo="#bf1e94"][vc_column_text css_animation=""]

I am text block. Click edit button to change this text. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.

[/vc_column_text][/historyinner][historyinner enable___title="true" enable___subtitle="true" title="Example Title" subtitle="Example SubTitle" enable___image="true" image_attachmentid="48" image_position="left" image_style="vc_box_shadow_circle_2" border_color="grey" enable___icon="false" enable___label="true" label_text="label" label_label="default" data_curve_x="0" data_curve_y="100" data_offset_start_x="0" data_offset_start_y="0" data_offset_end_x="0" data_offset_end_y="0" data_linewidth="10" data_linetype="round" direction="right" title_class="text-bold" image_size="full" icon_icon="0" icon_size="0" icon_rotate="0" icon_flip="0" icon_spin="0" icon_border="0" icon_shape="0" icon_position="0" grids___columns___mobile="12" grids___columns___tablet="10" grids___columns___small="10" grids___columns___large="10" grids___offset___mobile="0" grids___offset___tablet="2" grids___offset___small="2" grids___offset___large="2" grids___push___mobile="0" grids___push___tablet="0" grids___push___small="0" grids___push___large="0" grids___pull___mobile="0" grids___pull___tablet="0" grids___pull___small="0" grids___pull___large="0" left_grids___columns___mobile="12" left_grids___columns___tablet="6" left_grids___columns___small="6" left_grids___columns___large="6" left_grids___offset___mobile="0" left_grids___offset___tablet="0" left_grids___offset___small="0" left_grids___offset___large="0" left_grids___push___mobile="0" left_grids___push___tablet="0" left_grids___push___small="0" left_grids___push___large="0" left_grids___pull___mobile="0" left_grids___pull___tablet="0" left_grids___pull___small="0" left_grids___pull___large="0" right_grids___columns___mobile="12" right_grids___columns___tablet="6" right_grids___columns___small="6" right_grids___columns___large="6" right_grids___offset___mobile="0" right_grids___offset___tablet="0" right_grids___offset___small="0" right_grids___offset___large="0" right_grids___push___mobile="0" right_grids___push___tablet="0" right_grids___push___small="0" right_grids___push___large="0" right_grids___pull___mobile="0" right_grids___pull___tablet="0" right_grids___pull___small="0" right_grids___pull___large="0" css=".vc_custom_1437355679416{margin-bottom: 100px !important;}"][vc_column_text css_animation=""]

I am text block. Click edit button to change this text. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.

[/vc_column_text][/historyinner][/history][/vc_column][/vc_row]
CONTENT
    ));

    return $templates;
  }
}